### ISSUE TITLE
500: Internal_Server_Error

### ISSUE THREAD

**Issue by AvocadoVR** [BlueCatSoftware/Lyrix#2]
![image](https://github.com/BlueCatSoftware/Lyrix/assets/135179467/6423dd12-9ef5-4d05-b779-d85f22c1fecf)

I try to send a request to get lyrics but it keeps sending an error.

**Comment by AvocadoVR** [comment]
Or is there some way I can create my own version of yours. Not to sure what the .ENV contains.

**Comment by BlueCatSoftware** [comment]
> Or is there some way I can create my own version of yours. Not to sure what the .ENV contains.

You can message me on telegram @bluecatsoft
