### ISSUE TITLE
{"code":"ERR_UNESCAPED_CHARACTERS"}

### ISSUE THREAD

**Issue by Voravit09** [BlueCatSoftware/Lyrix#5]
When sending a request /WANYAi/เจ็บจนพอ (Enough)?remix=flash
Response {"code":"ERR_UNESCAPED_CHARACTERS"}
 Please fix the problem. Everything works fine when it's in English, but there's an error when it's in Thai.

**Comment by BlueCatSoftware** [comment]
I'm not sure thai characters ( i mean letters ) are used in official songs name in spotify and therefore the api don't support any characters other English for now, but you can always modify the repo to whatever you want.

**Comment by BlueCatSoftware** [comment]
this has been fixed @Voravit52

**Comment by BlueCatSoftware** [comment]
You can now use any characters
